{% set name = "bourbon" %}
{% set version = "7.3.0" %}
{% set sha256 = "8143795d2e11a6ea152814cf7386d5de048864f9fc1f5bcdd2ce1ea3bccf5f5e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/thoughtbot/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs

test:
  commands:
    - npm list -g bourbon
  requires:
    - nodejs


about:
  home: https://github.com/thoughtbot/bourbon
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: A Lightweight Sass Tool Set
  description: |
    Bourbon is a library of Sass mixins and functions that are designed to make 
    you a more efficient style sheet author.
  doc_url: http://bourbon.io/docs
  dev_url: https://github.com/thoughtbot/bourbon

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
