travis:
  secure:
    BINSTAR_TOKEN: mUNTA+b8CWFYbecRYB0pJ030WPtkqJlfWs2Do+yRwfr1yoUkmXJFtAsGjw1jTXuVZx2pA2N00iUcl2FS2v/WiMwzfEwJ2Ucs3oEOTtLTUJkDjpEJFTH550BvaXXLxX2JZ3tfjSrD+maU4XsLrrAqfVIeoPRVag5417WSByaxEoEBme4GqkRye2BlgOI1qjzO/6jxmW423TY7RRvWnk63G5KqxAgnFmDV29x+dfdblXH0BmhXppJxQek+sQABBTakmnbHNxUB1p4vV27dLKJwd8zjqOvxTPtWjSrnVNKFPCo6zz9R1kFK9/AdAAm3GQmxpGKR8bCydFQCOfoXGUoqe4q36Z/GRtDiNKCPhWYpuUG6v0ScdFS8q0WLtDZCmLhwX+u4D7B8GzI8/NhcrBx4PD4aYjZKJit8eyGMnCn3wQyUmPRyVBgOQosGshMJS7kSfJCoBjWbDy+lgYQY1bmbdH+9UElimY6z3WHToNh6OIerp++5wUN8cbiEvc+juDlWPJO4/oJ9TTpMAjjtUCO8fqBG8356vzLZ7hdy6x4ZwLIfmXcedsPLpFb54lSWO3pqSQ58YnQ92QtJSfZCjyqi7Znm/9lHCi/Y9tK/xKBqJVk58I5IC3AeO7cWegE8ceeK4KjY9GyvAJmJPPEToJ72YnHA94k6YNwW+12pLhFBY7A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
