travis:
  secure:
    BINSTAR_TOKEN: IgGTH+ar7Wxr9fPaefVmzz/A0XWxIP3UTupkDwhgI7cd2nBgeqQ/44GqcTT+cE66mssNx8YN4eNJwGz60R/p2XU4qcVB5ad9Wg/AtuwVx0+G47EpPJiBrHDzFQ27rH3g7zg/9ZZiggOJwD1Xn8aoGG1hQhtd42R1d1QsmR6G/44sFox20vq1eeztbiORHDhe7l4vi3cj8jkfAYMO7YW0FTXR6WVypsMUl1GZn6QaIvMlr4YbXWzw51gd+WfZE3CJ8zIzizqE3s03mjVYYq6Y0WAliD4zCMturId3Er0jWU0IuWcC5Gxbl31CH0UO3YfEvM9rLfYO3dmMtqxA3/lLgelq5VeLQ4L9tXJIa+y+fbEzQsR/7n0sI9RpVSsn7eaBsDI2fmH8sDysNmnlAF1Mo743MQJI4SBjQjFMd9TPa8ealWpsVWvbSfxFuEazJPlugXpIBRa+bw4j+LPRauFjod02Vj5vSburceM3xylJgjkJ1XTiEC6WzxMr4licBPMjfAXISz2vPtLRil6AcnLhZal3nVPg55r885F9lrHFcRCr0e3cl7j+YsaYqRFwCoT5TjA54i7rt83XiQmqhcRlLAC7VL6UGHEUU23vjaFDiWwk5LFE8VRtNQ3MxBqV3+csJx6e1eorS6M0nqmQzNqcJHOFyQZdHxQRiLmnRXs3qx0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
